### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by 0pendev** [nick92/launchy#1]
I am trying to test launchy on Xubuntu 18.04 but I get the following error when I type cmake .. -DCMAKE_INSTALL_PREFIX=/usr : 

> -- GSettings schemas will be installed locally.
> -- GSettings shemas will be compiled.
> -- GSettings schemas will be installed into /usr/share/glib-2.0/schemas/
> -- checking for Vala version of valac-0.26
> -- checking for a minimum Vala version of 0.26
> --   found Vala, version 0.40
> CMake Error at src/CMakeLists.txt:101 (include):
>   include could not find load file:
> GResource

**Comment by nick92** [comment]
should be fixed now, needed to add the file into cmake

**Comment by 0pendev** [comment]
Works perfectly now. Great Job. I will take a look at the code. Really the menu that was missing.
